export const INCREASE_POINTS = "INCREASE_POINTS";
export const UPDATE_AVARAGE_CLICK_TIME = "UPDATE_AVARAGE_CLICK_TIME";
export const LOCK_BONUS = "LOCK_BONUS";
export const INCREASE_CLICK_VALUE = "INCREASE_CLICK_VALUE";
export const DECREASE_POINTS = "DECREASE_POINTS";
export const SAVE_START_GAME_TIME = "SAVE_START_GAME_TIME";
export const INCREASE_PERMANENT_CLICKER_VALUE =
  "INCREASE_PERMANENT_CLICKER_VALUE";
export const CLEAR_STORAGE = "CLEAR_STORAGE";
